#
# Copyright 2019 Martin Goellnitz.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Install MySQL Client
  package: name=mysql-client-5.7 update_cache=yes

- name: Ensure remote Backup Directory
  file:
    path: /var/coremedia/backup
    owner: ubuntu
    group: ubuntu
    state: directory
    mode: '0755'
    
- name: Restore Script
  template: 
    src: restore.sh 
    dest: /opt/coremedia
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Push MLS Backup
  copy:
    dest: /var/coremedia/backup/cm_master.sql.xz
    src: "{{ backup_dir }}/cm_master.sql.xz"

- name: Push CMS Backup
  copy:
    dest: /var/coremedia/backup/cm_management.sql.xz
    src: "{{ backup_dir }}/cm_management.sql.xz"

- name: Stop Content Feeder
  service:
    name: content-feeder
    state: stopped
    
- name: Stop Solr
  service:
    name: solr
    state: stopped
    
- name: Wipe Studio Index
  shell: "rm -rf  /var/coremedia/solr-data/studio/data/*"

- name: Stop Master Live Server
  service:
    name: master-live-server
    state: stopped
    
- name: MLS Restore
  shell: "/opt/coremedia/restore.sh master"

- name: Stop Content Management Server
  service:
    name: content-management-server
    state: stopped
    
- name: CMS Restore
  shell: "/opt/coremedia/restore.sh content-management"

- name: Start Master Live Server
  service:
    name: master-live-server
    state: started

- name: Start Solr
  service:
    name: solr
    state: started

- name: Start Content Management Server
  service:
    name: content-management-server
    state: started

- name: Start Content Feeder
  service:
    name: content-feeder
    state: started
    
- name: Reset Preview CAEFeeder
  shell: "cd /opt/coremedia/caefeeder-preview-tools ; bin/cm resetcaefeeder reset"

- name: Re-Start CAEFeeder Preview
  service:
    name: caefeeder-preview
    state: restarted
